# Generated by Django 5.0.3 on 2024-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
