# Generated by Django 5.0.3 on 2024-04-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_amount_bid_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='bidAmount',
        ),
    ]
