# Generated by Django 5.0.3 on 2024-04-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bid_bid_bidamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidAmount',
            new_name='bid',
        ),
    ]
